language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: gBlGzEPIV/FDYdsRtwxX/LOoIkNAN3h26Mt+sw1L0RkB1A4ToY3Xc1JuWo0BZI7cYiZQ8z8hFKlDCVBkmYTg78TLMXw8Hn4u9gGZ3stTG9BgqSeehRH4XaaH+HzkzWp8gaOeyBW1jYhaRTFtYb/RlSoglttS3AGrh2XGZglwp1MiqHeQ+YBFFu5qTNso6Soh7qFBk8z7tA5LXwMcW/P0swQpyPAZS2lj07Bn0I9X9QBAF59757K324fXKHv1ApqdPKDrbVid8wPMww6vDLBPOcIBknfgvX8qkrsBE8QRmD362Aw8mkaIfZcfMZKHf14dJVmhf4Ayf12qCetC01GMQHqUEsTQL/WwDhCLNtwGbK1NZ5eKSMMZLeS6oWsfPHq3hh5RavOGroxuqzm3wJffluZhihXWZBn/BXXxN1vfrZgvR+7lnb3Nq7UYPJGTTchFUd/vETJSVeH67tAL5DjjyZqxCwt3rRpe2UOCsqMaIpgZIXd0dMiHg/0iiR9+ExSXblLX28+Ax/TmzWcdVXU5WrSgbxgaynfzptf36jABbnTw8i/TbcY1iASInC7X1sP1GTdFrBiImarwPBNEVRs3GSzvaBaqSOwEPRzFTdG9ph2VXgYjhR+Le1Alnl/6erRlxyZRPcq3/M3h/V6OIj8ULnMbob6QeeelaF8tyyDAZ18=
  app: boiling-gorge-25698
