language:          node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
env:
- CI=true
before_deploy:
- npm run build
deploy:
  provider:        heroku
  skip_cleanup:    true
  branches:
    only:
    - master
    - fix-20181024
  on:
    all_branches:  true
  api_key:         U+TVLClQQx4Hzhr+GJ+2uJJkv2gtmY/XRq3C0DeDng/+gvBBoJaGr1+TwxOB8S5hobvw0FTmfOoil8WYlMwsggxyVL7jXi+RKZBpYf2jEdWvk5kchvmdlZoiKJT+dZdjNkhVj6FLuBrFCfPpQekL07IgDhjJFVWHV23W2hQqtkJvdH+Iyi9Dexoh1Kq5A8Jd6hAyCA68X49XXkb1GPMYPR6uP28MzTgv37ncaaIvLECVptno4FLX40LzsxKZ/tKMVFb6O+TuZM014XiszzIsczIM/NNrhPcGPnsJKaGDLaHdUaiZLcHZbIwkQL/P71NuQ7+NJRxC7QHQlYBJeBW7XYIyNkWgmc7ZfmyPSdnZ1fjU5tXLlqlvdKNi0BG3tRRYfU4qkAcykoUOnmgwOkKF/F/ZqlYiACV5DtORasNTqP5e9fpkNi4sA8k1pInWoqESYhtRZw08a8pVGrwJ7SMkc1M+Hu+10wnysx2cDFIStZC4+o+NkR7eX1yCKz6eoh/RfBfdZOOEhKbGR8UB++LHqV8GCNCkE6jcRyM9a9JaY8dytc6P20ivitEtInmgPKQihS2FGU2qBRvgrpG1AWz2KD6sqOSz5rKRENKbPA6G6UP4pydwaMnFNEi38kU7786CvkWLbI8xvF7/kQren4aPF5T5+4ZG8PsTvHKPAykqVXE=
  app:             boiling-gorge-25698
