language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: a2e03a98-89e4-45cb-9d51-5d4789c1b860
  app: boiling-gorge-25698
  skip_cleanup: true
