language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
env:
- CI=true
before_deploy:
- npm run build
deploy:
  provider: heroku
  skip_cleanup: true
  branches:
    only:
    - master
    - fix-20181024
  on:
    all_branches: true
  api_key:
    secure: WtRSoVd5t1DScUQe5xcLc2bFy8obzO0dgR+0zV1PIpUin5FJvkUA0QcgrdiTfXq9XZXEYiS7A6I2ptBMfNtrjOD87v375Xud2McGnpSGRGv/rV40nfE9fa/K03aO9OLDzyLXGGTtyrFn5pqlXtPZQ8/BhF6+TFFD4ukIiY7sGomn4bDf4CgfO+7vm6sK5fSdcazBKuHYFJb9qMFC5Wbv/PbqcoZqGw+Uhq6rlU99La99m2MqA8U9qQxUek0LaVNTKF1Lk2xuWyXPqHUS3QpOv9Y9u0NYsJwM3zFYU/3fY9OAEAWoYcvUcql2Un7iOkWkX01/USEwUigXujiHtuBj3LGjQfoma0eIQIb6+++GXaTGTYaCqf88noPtUHrkjwUbQ3gYlIjvisAWyzB7/o3AwBBNBDxxHVTzmx3s3UBRtzh7ChiWhtAe9byeRip8vSNeJZPZCHF6TKxtx0BXeJaH/+4fwGUaz38UVtBmIKsISB6au8WKOGMpPUyeAwwQ7b6LLJO/eKS6cTozTiaKZWeJmJAUp0p4MU6Q3zP1claJ9AXF18WNdm84F00CwyumFjji9N/jWNZ2g8CGf4OeXJZ7NAB2iEaaTYUrCLsie+IqHWJ0tvQ7wnU8B3ZevUL41cBDs30p3c2CfXMuju3sJ8gUziHwhJ1Slb6uG++4dJruiAE=
  app: boiling-gorge-25698
