language:       node_js
node_js:        node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider:     heroku
  api_key:
    secure:     B3/uBGt96JT0eHYZb6qOI2DdtMEbTdzseDRSauiasMUdmkzaiEeD2nUnj5xGKGSdoVNribnZ8bde3LzVxgfF7KMl17kgBxGUOzwMTmL4fb7IzMg23wZjjte9qIrUCLsSWtolYHQYdK8VXVI4NHbj5O2mhRdh2dzBNVgdX2n3Br5C4l0CjtnG+Rzgeg9DWsqaGQtN2WCPIId9tjaRbn/5bUdqH8mLxL0cvIomCewz2Ie6DPeBvbhnV41XycIdRa1C4riBo0u/n+yo1j9lIlCjxfiKVuxEpPiR+CJl8ce2RW4hN5k9TE2sOTDQsk1Wd9VvHnWamZy+TcKGbfGdxWYXwlM4ozoWNk6/1OxWZHDaGoOi8Efs1HySc5IO+NzRZ+PgsBWqmI336aj7L3OBp1gDxX6qgjXCqOTxGj68vhipwuOjewi2Fvxm4VYsx1h5XHoDQh4StciaoNibxO7YOTJJGhIMwTr6daiwV6/Z6WQ3zwRV85IVspcvwTSS6Kq3RcIw67mDwYtt0qXxsfMhNyDwHj03icHUURE9OIPuYh+GiIPq8GKtiiYwCW4sP53DL5AlKLp8C8x9cZj/9XTtWtd2MMluPZ7t3vzgdK3+i2fPLM6akMRUO+OShI/sF3FVJt3hR8+NOsJP+KRf0yraGYoTVq2z0nvzN2i6hyLslahGyzk=
  app:          boiling-gorge-25698
